feat: POST /translations/:user_id 개발 및 테스트 작성
my-hand-translator/my-hand-translator-backend pull request #4
Opened 2021-09-07 12:32 UTC by jch1223

2021-09-07 13:58 UTC, kenhuh commented on controllers/translationController.js
> +    return next(createHttpError(500, DB.MONGOOSE_ERROR));
몽구스 에러가 발생했다는 정보가 클라이언트에게 전달되는건 부적절해 보입니다. TMI에요.

2021-09-07 14:00 UTC, kenhuh commented on spec/translations/user_id.js
> +  before((done) => {
모카 버젼에 따라 async 사용 가능합니다.

```js
beforeEach(async function() {
  await db.clear();
  await db.save([tobi, loki, jane]);
});
```

2021-09-07 14:02 UTC, kenhuh commented
변수명 수정한 커밋은 feat 커밋과 squash 하는게 좋을것 같아요. 굳이 별도로 빠져야 할 필요는 없을것 같습니다.

2021-09-07 14:04 UTC, kenhuh commented on middlewares/validateTranslations.js
> +    }
조금 더 섬세하게 validation 하자면, 다양한 케이스가 있을 수 있을것 같아요. 예를 들어 text에 공백만 들어오는 경우라던지 등등..

2021-09-07 14:05 UTC, kenhuh commented
지금 미들웨어 디렉토리에 함수 단위로 파일이 만들어지는거 같은데, 미들웨어도 카테고리 별로 그룹핑을 해주는게 좋을것 같아요. 함수 기능 단위로 별도 파일을 만들어 관리하는 방향은 장기적이지 못한것 같아요.

2021-09-07 17:20 UTC, aidencoders approved these changes

2021-09-07 17:20 UTC, aidencoders commented on spec/translations/user_id.js
> +      .post(`/translations/asdf`)
```suggestion
      .post("/translations/asdf")
```

실수하신것 같아요 !

2021-09-08 05:03 UTC, sounmind requested changes

2021-09-08 05:03 UTC, sounmind commented on constants/responseMessages.js
> +  COMMON: {
응답 메시지를 관리하는 파일이므로, 아래와 같이 작성해주시면 자연스러울 것 같습니다.

```javascript
RESULT: {
  OK: "ok",
  ERROR: "error",
  FAIL: "fail",
}
```

2021-09-08 06:09 UTC, aidencoders requested changes

2021-09-08 06:09 UTC, aidencoders commented on spec/translations/user_id.js
> +const Translation = require("../../models/User");
User model을 require 하는데, 변수명은 Tanslation 이네요.

밑에 맥락상 Translation model을 require 해야 할 것 같아요 !

2021-09-08 06:38 UTC, sounmind requested changes

2021-09-08 06:38 UTC, sounmind commented on constants/error.js
> +    INTERNAL_ERROR: "Internal Server Error",
```
INTERNAL_ERROR: "Internal server error.",
```

2021-09-08 06:40 UTC, sounmind approved these changes

2021-09-08 06:41 UTC, aidencoders approved these changes

2021-09-08 06:44 UTC, merged