feat: 특정 번역 기록 지우기
my-hand-translator/my-hand-translator-backend pull request #8
Opened 2021-09-08 12:34 UTC by aidencoders

- 클라이언트로부터 `translation_id`를 받아 번역기록 삭제
- 테스트케이스 작성
- 9/9 task card 미리 개발

2021-09-08 12:44 UTC, jch1223 commented on controllers/translationController.js
> +  deleteTranslation,
파일 명에 Translation이 명시 되어있어서 생략해도 되지 않을까 합니다

2021-09-08 12:44 UTC, jch1223 commented on spec/translations/translationDelete.js
> +        await Translation.findOneAndDelete({ user: "test@gmail.com" });
```suggestion
        await Translation.findByIdAndDelete(translationId);
```
이렇게 하면 좀 더 의존성 없는 테스트 코드가 될 것 같습니다

2021-09-08 12:44 UTC, jch1223 commented on spec/translations/translationDelete.js
> +        .send({})
```suggestion
```
생략 가능할듯합니다

2021-09-09 04:02 UTC, sounmind requested changes

2021-09-09 04:02 UTC, sounmind commented on routes/translations.js
> +  deleteTranslation,
위에서 철희님이 말씀하신 것처럼
 deleteTranslation -> delete
이 낫겠네요!

2021-09-09 04:15 UTC, aidencoders commented on routes/translations.js
> +  deleteTranslation,
`delet`가 예약어라서 린트 설정에 걸리기도 하고, 쓰기에 애매한 것 같아요 ! 

더 좋은 방법이 있을까요 ?

2021-09-09 04:16 UTC, aidencoders commented on spec/translations/translationDelete.js
> +        await Translation.findOneAndDelete({ user: "test@gmail.com" });
`translationId`를 다른곳에서 필요해서 쓰기 전에 작성 해 뒀던 것인데 누락되었네요.

확인 감사합니다 !

2021-09-09 04:40 UTC, sounmind commented on routes/translations.js
> +  deleteTranslation,
흠...생각을 해봅시다. @jch1223 철희님도 같이 이야기해보아요!

저는 remove 는 어떤가 하네요?

2021-09-09 04:44 UTC, jch1223 commented on routes/translations.js
> +  deleteTranslation,
저도 remove 좋아보입니다

2021-09-09 04:47 UTC, aidencoders commented on routes/translations.js
> +  deleteTranslation,
저도 remove 좋아보이네요 ! 반영 👍

2021-09-09 08:09 UTC, merged